# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: modelops-cluster
  region: eu-west-3

iam:
  withOIDC: true
  
nodeGroups:
  - name: modelops-nodegroup
    instanceType: t3.medium 
    desiredCapacity: 2      
    volumeSize: 20          
