# templates/mlflow.yml
{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: {{ .Values.mlflow.service.type | default "NodePort" }}
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: {{ .Values.mlflow.service.port }}
      targetPort: 5000
      {{- if eq .Values.mlflow.service.type "NodePort" }}
      nodePort: {{ .Values.mlflow.service.nodePort }}
      {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: {{ .Values.mlflow.replicaCount }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      serviceAccountName: {{ .Values.mlflow.serviceAccountName | default "default" }}
      containers:
      - name: mlflow
        image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 5000
        {{- if .Values.mlflow.env }}
        env:
        {{- range $key, $value := .Values.mlflow.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.mlflow.probes.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.mlflow.resources.requests.cpu }}
            memory: {{ .Values.mlflow.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mlflow.resources.limits.cpu }}
            memory: {{ .Values.mlflow.resources.limits.memory }}
        command: ["mlflow", "server",
              "--host", "0.0.0.0",
              "--port", "5000",
              "--default-artifact-root", "s3://{{ .Values.mlflow.s3BucketName }}/"]
{{- end}}